@startuml sequence_login

actor User
boundary View
control Controller
entity Model
participant GoogleAPI

User -> Controller: Yêu cầu đăng nhập
Controller -> GoogleAPI: Yêu cầu Google đăng nhập
GoogleAPI -> Controller: Google Login URL
Controller -> User: Chuyển hướng đến Google đăng nhập
User -> GoogleAPI: Gửi thông tin xác thực Google
GoogleAPI -> User: Xác thực thông tin Google
User -> GoogleAPI: Cấp phép truy cập
GoogleAPI -> Controller: Google Access Token
Controller -> Model: Lưu dữ liệu người dùng
Model -> Controller: Dữ liệu người dùng đã lưu
Controller -> User: Đăng nhập thành công

@enduml
